POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "zet",
    "password": "zet"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "zet",
    "password": "zet"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkyYmJiNGEyZWNkNTI0NjhlZGRkNDMiLCJpYXQiOjE2NzA1NzMwNjl9.0F9lvPWG9foBQVIoJ2YQj8Tm_Rx8mWsMRatbsUxJGXA

{
    "title": "third post",
    "description": "third post description",
    "url":"bootstrap.org",
    "status": "TO LEARN"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzk2YjEzZjI5Y2ZkMDBmOTFjM2VhNGQiLCJpYXQiOjE2NzA4OTgzMTR9.8L5rADoZQfoRJNZuEKLkB1mfsOFFRWpl_WYRJVtCCFc

###
PUT  http://localhost:5000/api/posts/639150f732f0ebeb148bf11c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkwNzIwMWE0ZDZkZmJjMjBmZjA4M2MiLCJpYXQiOjE2NzA0NzE2MzV9.XXY1yACGKa0s2s0UIE3lE35L2xDOpRP-bClabFcxfK0

{
    "title":"React",
    "description":"React for developers",
    "url":"reactjs.org",
    "status":"LEARNING"
}

###
DELETE  http://localhost:5000/api/posts/63915ce0996c92799637001b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkwNzIwMWE0ZDZkZmJjMjBmZjA4M2MiLCJpYXQiOjE2NzA0NzE2MzV9.XXY1yACGKa0s2s0UIE3lE35L2xDOpRP-bClabFcxfK0
